- id: '1570640910196'
  alias: Bedroom heater on
  trigger:
  - entity_id: sensor.aeon_labs_zw120_door_window_sensor_gen5_access_control_2
    from: '22'
    platform: state
    to: '23'
  condition: []
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.danfoss_devolo_home_control_radiator_thermostat_heating_1
      temperature: 21
- id: '1570640910197'
  alias: Bedroom heater off
  trigger:
  - entity_id: sensor.aeon_labs_zw120_door_window_sensor_gen5_access_control_2
    from: '23'
    platform: state
    to: '22'
  condition: []
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.danfoss_devolo_home_control_radiator_thermostat_heating_1
      temperature: 4
