- id: bedroom-heater-morning
  trigger:
  - at: 07:00:00
    platform: time
  - at: '14:00:00'
    platform: time
  action:
  - data:
      entity_id: climate.danfoss_devolo_home_control_radiator_thermostat_heating_1
      temperature: 21
    service: climate.set_temperature
- id: bedroom-heater-evening
  trigger:
  - at: '22:00:00'
    platform: time
  - at: '12:00:00'
    platform: time
  action:
  - data:
      entity_id: climate.danfoss_devolo_home_control_radiator_thermostat_heating_1
      temperature: 7
    service: climate.set_temperature
